# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yemzo Nigeria Limited
email: info@yemzo.com.ng
description: > # this means to ignore newlines until "baseurl:"
  Yemzo Shipping & Logistics is a fully integrated worldwide service provider 
  dedicated to serving the Shipping, Logistics and 
  Marine Markets through an international.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: yemzo
github_username:  yemzo

# Build settings
markdown: kramdown

#To stop Jekyll including your configuration in it’s generated site
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']