source 'https://rubygems.org'
# ruby '2.2.3'
ruby '2.3.0'
gem 'bundler'
gem 'jekyll'
gem 'kramdown'
gem 'rack-jekyll'
gem 'rake'
gem 'puma'
gem 'jekyll-watch', '~> 1.3', '>= 1.3.1'
gem 'font-awesome-sass'
